### ISSUE TITLE
OpenSSL verification error

### ISSUE THREAD

**Issue by larubbio** [snowplow/snowplow-ruby-tracker#110] opened 2019-07-25 15:54 UTC
I'm getting an error when I connect to an https endpoint:

> OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed

I'm able to fix it locally by modifying emitter.rb:

```ruby
       if destination.scheme == 'https'
         http.use_ssl = true
         store = OpenSSL::X509::Store.new
         store.set_default_paths
         http.cert_store = store
       end
```

However I'm not sure what impact that may have on other users of the library.

**Comment by mscwilson** [comment] 2021-10-05 13:40
Hi @larubbio. Thanks for letting us know about your error, and sorry for taking so long to get back to you about it.

I haven't been able to recreate the error myself. Do you by any chance remember any more details about what happened, such as what you were working on when the error appeared? Or if one specific https endpoint caused the problem?

**Comment by mscwilson** [comment] 2022-03-31 14:38
We were unable to reproduce the error, so I'm closing this.

**Closed by mscwilson** 2022-03-31 14:38 UTC
Labels: type:defect, category:help_wanted
